# Generated by Django 2.0.2 on 2018-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0004_auto_20171126_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podesavanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scraping', models.BooleanField(default=False)),
            ],
        ),
    ]
